In [1]:
source("./filter-ABC.R")
test<-read.csv("/data/coro_data.csv")
options(warn = -1 )
library("xtable")

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Loading required package: spatstat.data

Loading required package: spatstat.univar

spatstat.univar 3.0-1

Loading required package: spatstat.geom

spatstat.geom 3.3-3

Loading required package: spatstat.random

spatstat.random 3.3-2

Loading required package: spatstat.explore

Loading required package: nlme


Attaching package: ‘nlme’


The following object is masked from ‘package:dplyr’:

    collapse


spatstat.explore 3.3-2

Loading required package: spatstat.model

Loading required package: rpart

spatstat.model 3.3-2

Loading required package: spatstat.linnet

spatstat.linnet 3.2-2


spatstat 3.2-1
For an introduction to spatstat, type ‘beginner’

## Additional filter test for ABC dataset

In [2]:
test = test %>% rename(x = x_section, y = y_section)

In [3]:
section_filter <- function(data,sec,is_exc){
    li<- output_sample(test, sec)
    if (is_exc == TRUE){    
        type <- li$et
        data<-li$edata
    }
    else{
        type <- li$it
        data<-li$idata
    }
    pp<- create_pp(type,data)
    nn<-calc_R(pp, type, 0.2)
    conf<- calc_conf(pp, type, test, sec)
    res<-intense_qualify(pp,type, nn, conf)
    col.name<-paste('%',toString(sec), sep='')
    df<- data.frame(cluster = res$cluster, coln = round(res$conf,2))
    names(df)[names(df) == "coln"] <- col.name
    return(df)
}

### Excitatory cells

In [4]:
for (n in 59:61){
    nam <- paste('df',toString(n), sep='')
    assign(nam, section_filter(test, n, TRUE))
}

[1]   136 10210    29
[1]  130 1215   23
[1] "0109 L2/3 IT CTX Glut_2"
[1] 0.65
[1] "0436 L6 CT CTX Glut_1"
[1] 0.75
[1] "0072 L4/5 IT CTX Glut_1"
[1] 0.6
[1] "0091 L4/5 IT CTX Glut_4"
[1] 0.45
[1] "0105 L2/3 IT CTX Glut_1"
[1] 0.5
[1] "0054 L6 IT CTX Glut_5"
[1] 0.6
[1] "0444 L6 CT CTX Glut_2"
[1] 0.6
[1] "0351 L5 ET CTX Glut_1"
[1] 0.55
[1] "0104 L2/3 IT CTX Glut_1"
[1] 0.65
[1] "0095 L4/5 IT CTX Glut_5"
[1] 0.6
[1] "0042 L6 IT CTX Glut_2"
[1] 0.65
[1] "0082 L4/5 IT CTX Glut_2"
[1] 0.5
[1] "0117 L2/3 IT CTX Glut_4"
[1] 0.55
[1] "0084 L4/5 IT CTX Glut_3"
[1] 0.45
[1] "0360 L5 ET CTX Glut_2"
[1] 0.5
[1] "0118 L2/3 IT CTX Glut_4"
[1] 0.7
[1] "0364 L5 ET CTX Glut_2"
[1] 0.65
[1] "0070 L4/5 IT CTX Glut_1"
[1] 0.45
[1] "0442 L6 CT CTX Glut_2"
[1] 0.7
[1] "0098 L4/5 IT CTX Glut_5"
[1] 0.45
[1] "0087 L4/5 IT CTX Glut_3"
[1] 0.6
[1] "0088 L4/5 IT CTX Glut_3"
[1] 0.6
[1] "0094 L4/5 IT CTX Glut_4"
[1] 0.8
[1] "0468 L5 NP CTX Glut_3"
[1] 0.4
[1] "0061 L5 IT CTX Glut_3"
[1] 0.55
[1] "0090 L4/5 IT CTX Glut_4"
[1] 0.75
[1] "0350 L5 ET CTX Glut_1"
[1] 0.45
[1] "0023 L5/6 IT TPE-ENT Glut_1"
[1] 0.35
[1] "0078 L4/5 IT CTX Glut_2"
[1] 0.5
[1]   99 6548   26
[1] 125 937  23
[1] "0109 L2/3 IT CTX Glut_2"
[1] 0.7
[1] "0095 L4/5 IT CTX Glut_5"
[1] 0.6
[1] "0072 L4/5 IT CTX Glut_1"
[1] 0.5
[1] "0082 L4/5 IT CTX Glut_2"
[1] 0.4
[1] "0444 L6 CT CTX Glut_2"
[1] 0.65
[1] "0084 L4/5 IT CTX Glut_3"
[1] 0.35
[1] "0091 L4/5 IT CTX Glut_4"
[1] 0.45
[1] "0117 L2/3 IT CTX Glut_4"
[1] 0.55
[1] "0105 L2/3 IT CTX Glut_1"
[1] 0.35
[1] "0436 L6 CT CTX Glut_1"
[1] 0.65
[1] "0054 L6 IT CTX Glut_5"
[1] 0.65
[1] "0351 L5 ET CTX Glut_1"
[1] 0.45
[1] "0468 L5 NP CTX Glut_3"
[1] 0.65
[1] "0087 L4/5 IT CTX Glut_3"
[1] 0.45
[1] "0078 L4/5 IT CTX Glut_2"
[1] 0.55
[1] "0104 L2/3 IT CTX Glut_1"
[1] 0.5
[1] "0360 L5 ET CTX Glut_2"
[1] 0.65
[1] "0077 L4/5 IT CTX Glut_2"
[1] 0.4
[1] "0088 L4/5 IT CTX Glut_3"
[1] 0.6
[1] "0094 L4/5 IT CTX Glut_4"
[1] 0.8
[1] "0098 L4/5 IT CTX Glut_5"
[1] 0.65
[1] "0042 L6 IT CTX Glut_2"
[1] 0.7
[1] "0039 L6 IT CTX Glut_2"
[1] 0.4
[1] "0473 L5 NP CTX Glut_4"
[1] 0.4
[1] "0464 L5 NP CTX Glut_2"
[1] 0.65
[1] "0118 L2/3 IT CTX Glut_4"
[1] 0.65
[1]   81 6476   20
[1] 107 988  19
[1] "0109 L2/3 IT CTX Glut_2"
[1] 0.6
[1] "0095 L4/5 IT CTX Glut_5"
[1] 0.65
[1] "0117 L2/3 IT CTX Glut_4"
[1] 0.4
[1] "0091 L4/5 IT CTX Glut_4"
[1] 0.5
[1] "0072 L4/5 IT CTX Glut_1"
[1] 0.6
[1] "0084 L4/5 IT CTX Glut_3"
[1] 0.6
[1] "0105 L2/3 IT CTX Glut_1"
[1] 0.45
[1] "0351 L5 ET CTX Glut_1"
[1] 0.65
[1] "0054 L6 IT CTX Glut_5"
[1] 0.7
[1] "0082 L4/5 IT CTX Glut_2"
[1] 0.45
[1] "0087 L4/5 IT CTX Glut_3"
[1] 0.5
[1] "0077 L4/5 IT CTX Glut_2"
[1] 0.4
[1] "0468 L5 NP CTX Glut_3"
[1] 0.65
[1] "0088 L4/5 IT CTX Glut_3"
[1] 0.7
[1] "0094 L4/5 IT CTX Glut_4"
[1] 0.55
[1] "0078 L4/5 IT CTX Glut_2"
[1] 0.45
[1] "0118 L2/3 IT CTX Glut_4"
[1] 0.6
[1] "0104 L2/3 IT CTX Glut_1"
[1] 0.65
[1] "0023 L5/6 IT TPE-ENT Glut_1"
[1] 0.45
[1] "0098 L4/5 IT CTX Glut_5"
[1] 0.3

### Inhibitory cells

In [5]:
for (n in 59:61){
    nam <- paste('dfi',toString(n), sep='')
    assign(nam, section_filter(test, n, FALSE))
}

[1]   136 10210    29
[1]  130 1215   23
[1] "0740 Pvalb Gaba_3"
[1] 0.5
[1] "0743 Pvalb Gaba_4"
[1] 0.6
[1] "0709 Lamp5 Gaba_1"
[1] 0.35
[1] "0742 Pvalb Gaba_3"
[1] 0.3
[1] "0707 Lamp5 Gaba_1"
[1] 0.6
[1] "0780 Sst Gaba_4"
[1] 0.5
[1] "0803 Sst Gaba_10"
[1] 0.7
[1] "0792 Sst Gaba_7"
[1] 0.45
[1] "0741 Pvalb Gaba_3"
[1] 0.4
[1] "0754 Pvalb Gaba_8"
[1] 0.35
[1] "0645 Vip Gaba_6"
[1] 0.7
[1] "0708 Lamp5 Gaba_1"
[1] 0.75
[1] "0718 Lamp5 Gaba_2"
[1] 0.8
[1] "0756 Sst Gaba_1"
[1] 0.4
[1] "0798 Sst Gaba_9"
[1] 0.05
[1] "0779 Sst Gaba_4"
[1] 0.2
[1] "0800 Sst Gaba_9"
[1] 0.1
[1] "0793 Sst Gaba_7"
[1] 0.2
[1] "0819 Sst Gaba_16"
[1] 0.05
[1] "0747 Pvalb Gaba_4"
[1] 0.15
[1] "0640 Vip Gaba_5"
[1] 0.6
[1] "0643 Vip Gaba_5"
[1] 0.1
[1] "0820 Sst Gaba_16"
[1] 0.25
[1]   99 6548   26
[1] 125 937  23
[1] "0740 Pvalb Gaba_3"
[1] 0.55
[1] "0709 Lamp5 Gaba_1"
[1] 0.35
[1] "0743 Pvalb Gaba_4"
[1] 0.55
[1] "0742 Pvalb Gaba_3"
[1] 0.4
[1] "0707 Lamp5 Gaba_1"
[1] 0.3
[1] "0754 Pvalb Gaba_8"
[1] 0.45
[1] "0780 Sst Gaba_4"
[1] 0.6
[1] "0803 Sst Gaba_10"
[1] 0.25
[1] "0741 Pvalb Gaba_3"
[1] 0.4
[1] "0792 Sst Gaba_7"
[1] 0.5
[1] "0779 Sst Gaba_4"
[1] 0.45
[1] "0793 Sst Gaba_7"
[1] 0.1
[1] "0645 Vip Gaba_6"
[1] 0.15
[1] "0736 Pvalb Gaba_1"
[1] 0.05
[1] "0795 Sst Gaba_8"
[1] 0.45
[1] "0718 Lamp5 Gaba_2"
[1] 0.15
[1] "0758 Sst Gaba_1"
[1] 0.05
[1] "0708 Lamp5 Gaba_1"
[1] 0.2
[1] "0744 Pvalb Gaba_4"
[1] 0.15
[1] "0797 Sst Gaba_8"
[1] 0.6
[1] "0760 Sst Gaba_1"
[1] 0.05
[1] "0776 Sst Gaba_4"
[1] 0.05
[1] "0798 Sst Gaba_9"
[1] 0.5
[1]   81 6476   20
[1] 107 988  19
[1] "0740 Pvalb Gaba_3"
[1] 0.6
[1] "0709 Lamp5 Gaba_1"
[1] 0.55
[1] "0742 Pvalb Gaba_3"
[1] 0.25
[1] "0741 Pvalb Gaba_3"
[1] 0.45
[1] "0803 Sst Gaba_10"
[1] 0.8
[1] "0707 Lamp5 Gaba_1"
[1] 0.45
[1] "0743 Pvalb Gaba_4"
[1] 0.7
[1] "0754 Pvalb Gaba_8"
[1] 0.25
[1] "0792 Sst Gaba_7"
[1] 0.35
[1] "0645 Vip Gaba_6"
[1] 0.5
[1] "0795 Sst Gaba_8"
[1] 0.45
[1] "0718 Lamp5 Gaba_2"
[1] 0.15
[1] "0708 Lamp5 Gaba_1"
[1] 0.45
[1] "0780 Sst Gaba_4"
[1] 0.05
[1] "0797 Sst Gaba_8"
[1] 0.65
[1] "0798 Sst Gaba_9"
[1] 0.4
[1] "0751 Pvalb Gaba_6"
[1] 0.35
[1] "0642 Vip Gaba_5"
[1] 0.3
[1] "0744 Pvalb Gaba_4"
[1] 0.2

### Merge all qualified cell types from sections  
**Excitatory clusters**

In [6]:
df_list <- list(df59, df60, df61)      
# merge all data frames together
df<-Reduce(function(x, y) merge(x, y, all=TRUE), df_list)  
df

   cluster                 %59  %60  %61
1  0042 L6 IT CTX Glut_2   0.63 0.55   NA
2  0061 L5 IT CTX Glut_3   0.54   NA   NA
3  0070 L4/5 IT CTX Glut_1 0.65   NA   NA
4  0072 L4/5 IT CTX Glut_1 0.72 0.65 0.75
5  0077 L4/5 IT CTX Glut_2   NA 0.61 0.70
6  0078 L4/5 IT CTX Glut_2 0.82 0.82 0.82
7  0082 L4/5 IT CTX Glut_2 0.59 0.63 0.57
8  0084 L4/5 IT CTX Glut_3 0.70 0.65 0.74
9  0087 L4/5 IT CTX Glut_3   NA 0.71 0.72
10 0088 L4/5 IT CTX Glut_3 0.56 0.44   NA
11 0091 L4/5 IT CTX Glut_4 0.70 0.59 0.70
12 0094 L4/5 IT CTX Glut_4   NA   NA 0.60
13 0095 L4/5 IT CTX Glut_5 0.74 0.76 0.79
14 0098 L4/5 IT CTX Glut_5 0.57 0.56   NA
15 0104 L2/3 IT CTX Glut_1 0.77 0.65 0.73
16 0105 L2/3 IT CTX Glut_1 0.81 0.76 0.81
17 0109 L2/3 IT CTX Glut_2 0.71 0.63 0.68
18 0117 L2/3 IT CTX Glut_4 0.72 0.67 0.74
19 0118 L2/3 IT CTX Glut_4 0.51   NA   NA
20 0350 L5 ET CTX Glut_1   0.92   NA   NA
21 0351 L5 ET CTX Glut_1   0.72 0.57 0.74
22 0364 L5 ET CTX Glut_2   0.58   NA   NA
23 0436 L6 CT CTX Glut_1   0.79 0.78   NA
24 0444 L6 CT CTX Glut_2   0.69   NA   NA
25 0468 L5 NP CTX Glut_3     NA   NA 0.80
26 0473 L5 NP CTX Glut_4     NA 0.61   NA

**Inhibitory clusters**

In [7]:
dfi_list <- list(dfi59, dfi60, dfi61)      
#merge all data frames together
dfi<-Reduce(function(x, y) merge(x, y, all=TRUE), dfi_list)  
dfi

  cluster           %59  %60  %61
1 0740 Pvalb Gaba_3   NA 0.50 0.65
2 0741 Pvalb Gaba_3   NA 0.44   NA
3 0742 Pvalb Gaba_3 0.44   NA 0.69
4 0743 Pvalb Gaba_4 0.43   NA   NA
5 0776 Sst Gaba_4     NA 0.69   NA
6 0798 Sst Gaba_9   0.60   NA   NA
7 0803 Sst Gaba_10    NA 0.42   NA
8 0819 Sst Gaba_16  0.52   NA   NA

In [8]:
write.csv(df, "./filter-exc.csv",row.names = FALSE)

In [9]:
write.csv(dfi, "./filter-inhib.csv",row.names = FALSE)

## Hypothesis testing on qualified types

In [2]:
df<- read.csv("./filter-inhib.csv")
df1 <- replace(df, is.na(df), 0)
df1[df1<=0.5] <- NA
df1<-df1[rowSums(is.na(df1)) != ncol(df1)-1, ]
row.names(df1) <- NULL
types1 = df1$cluster
types1

[1] "0740 Pvalb Gaba_3" "0742 Pvalb Gaba_3" "0776 Sst Gaba_4"

In [3]:
sections1<- apply(df1[,-1], 1, function(i) colnames(df1[,-1])[ !is.na(i) ]) ## qualified colns
sections1<- sapply(sections1, function(x){as.numeric(gsub("X.", "", x))})
sections1

X.61 X.61 X.60
  61   61   60

In [18]:
source("./scale.R")
options(warn=-1)

In [19]:
## Create point patterns
pp1<-create_pp(test, NULL,sections1[[1]], types1[1])
pp2<-create_pp(test, NULL,sections1[[2]], types1[2])
pp3<-create_pp(test, NULL,sections1[[3]], types1[3])

In [32]:
npp <-npoints(pp1[[1]])
Wpp <-Window(pp1[[1]])
pp.base <-rSSI(npp, r=0.01, Wpp, nsim=199)
dclf.test(pp1[[1]], Lest, simulate=pp.base, nsim=199, rinterval=c(0,0.05), alternative='less',verbose=FALSE)$p.value

Generating 199 realisations...
1, 2, 3, 4.6.8.10.12.14.16.18.20.22.24.26.28.30.32.34
.36.38.40.42.44.46.48.50.52.54.56.58.60.62.64.66.68.70.72.74
.76.78.80.82.84.86.88.90.92.94.96.98.100.102.104.106.108.110.112.114
.116.118.120.122.124.126.128.130.132.134.136.138.140.142.144.146.148.150.152.154
.156.158.160.162.164.166.168.170.172.174.176.178.180.182.184.186.188.190.192.194
.196.198
199.

[1] 0.005

In [42]:
npp <-npoints(pp2[[1]])
Wpp <-Window(pp2[[1]])
pp.base <-rSSI(npp, r=0.01, Wpp, nsim=199)
dclf.test(pp2[[1]], Lest, simulate=pp.base, nsim=199, rinterval=c(0,0.05), alternative='less',verbose=FALSE)$p.value

Generating 199 realisations...
1, 2, 3, 4.6.8.10.12.14.16.18.20.22.24.26.28.30.32.34
.36.38.40.42.44.46.48.50.52.54.56.58.60.62.64.66.68.70.72.74
.76.78.80.82.84.86.88.90.92.94.96.98.100.102.104.106.108.110.112.114
.116.118.120.122.124.126.128.130.132.134.136.138.140.142.144.146.148.150.152.154
.156.158.160.162.164.166.168.170.172.174.176.178.180.182.184.186.188.190.192.194
.196.198
199.

[1] 0.005

In [44]:
npp <-npoints(pp3[[1]])
Wpp <-Window(pp3[[1]])
pp.base <-rSSI(npp, r=0.01, Wpp, nsim=199)
dclf.test(pp3[[1]], Lest, simulate=pp.base, nsim=199, rinterval=c(0,0.1), alternative='less',verbose=FALSE)$p.value

Generating 199 realisations...
1, 2, 3, 4.6.8.10.12.14.16.18.20.22.24.26.28.30.32.34
.36.38.40.42.44.46.48.50.52.54.56.58.60.62.64.66.68.70.72.74
.76.78.80.82.84.86.88.90.92.94.96.98.100.102.104.106.108.110.112.114
.116.118.120.122.124.126.128.130.132.134.136.138.140.142.144.146.148.150.152.154
.156.158.160.162.164.166.168.170.172.174.176.178.180.182.184.186.188.190.192.194
.196.198
199.

[1] 0.04